import time
import os
import job_hiring
def intro():
  os.system('clear')
  print("It's a new day. It's your time to shine.")
  time.sleep(2)
  print("It's time to take your career into your own hands.")
  time.sleep(2)
  print("You've saved up all your money, great!")
  time.sleep(2)
  print("Now it's time to put all your eggs into one basket and take a huge gamble on your future.\nA gamble that comes with a 100% chance of success (in some cases).")
  time.sleep(5)
  print("What are we talking about? We're talking about becoming a Home Depot franchise.")
  time.sleep(3)
  print("That's right. Hardware store ownership and management.")
  time.sleep(2)
  print("Something almost anyone can do with a limited degree of success.")
  time.sleep(2)
  print("Sure, it's a lot of money to invest. But everyone's doing it.")
  time.sleep(2)
  print("And that means it's safe and lucrative.")
  time.sleep(3)
  print("With your initial investment, you'll receive everything you need to get started: A location, power, and a few shelves.")
  time.sleep(5)
  print("This concludes the help we are legally obligated to provide.")
  time.sleep(3)
  print("Your journey begins!\nPress Enter to continue.")
  input()
  os.system('clear')
  job_hiring.hire()