import time
import os
import job_hiring
def intro(s):
  multiForSkip = 1
  os.system('clear')
  print("It's a new day. It's your time to shine.")
  time.sleep(2 * multiForSkip)
  print("It's time to take your career into your own hands.")
  time.sleep(2 * multiForSkip)
  print("You've saved up all your money, great!")
  time.sleep(2 * multiForSkip)
  print("Now it's time to put all your eggs into one basket and take a huge gamble on your future.")
  time.sleep(2 * multiForSkip)
  print("A gamble that comes with a 100% chance of success (in some cases).")
  time.sleep(5 * multiForSkip)
  print("What are we talking about? We're talking about becoming a Home Depot franchisee.")
  time.sleep(3 * multiForSkip)
  print("That's right. Hardware store ownership and management.")
  time.sleep(2 * multiForSkip)
  print("Something almost anyone can do with a limited degree of success.")
  time.sleep(2 * multiForSkip)
  print("Sure, it's a lot of money to invest. But everyone's doing it.")
  time.sleep(2 * multiForSkip)
  print("And that means it's safe and lucrative.")
  time.sleep(3 * multiForSkip)
  print("With your initial investment, you'll receive everything you need to get started:\nA location, power, and a few shelves.")
  time.sleep(5 * multiForSkip)
  print("This concludes the help we are legally obligated to provide.")
  time.sleep(3 * multiForSkip)
  print("Your journey begins!\nPress Enter to continue.")
  input()
  os.system('clear')
  print("We recommend hiring some employees to begin with. No employees means no profit!")
  job_hiring.job_hire_first_time(s)